twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"
        cartService: "@App\\Cart\\CartService"
        google_maps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
        recaptcha3_key: '%env(RECAPTCHA3_KEY)%'