App\Entity\Contact:
  properties:
    nom:
      - NotBlank: { message: "YAML Le nom est obligatoire" }
      - Length: {
        min: 2, 
        max: 255, 
        minMessage: "Caracteres + de 2 merci"}
    prenom:
      - NotBlank: { message: "YAML Le prénom est obligatoire"}